import {useEffect,useRef,type ReactNode} from 'react';
import * as echarts from 'echarts';
import {useReactTable,getCoreRowModel,flexRender,type ColumnDef} from '@tanstack/react-table';
import {AlertCircle,ChevronLeft,ChevronRight,LoaderCircle} from 'lucide-react';
import {Button} from './ui/button';
import {human} from '../api';
export function State({query,children}:{query:any;children:(data:any)=>ReactNode}){if(query.isPending)return <div className="state"><LoaderCircle className="spin"/>Loading investigation data…</div>;if(query.error)return <div className="state error"><AlertCircle/><strong>Could not load data</strong><p>{query.error.message}</p><Button variant="outline" onClick={()=>query.refetch()}>Try again</Button></div>;return <>{children(query.data)}</>;}
export function Badge({value}:{value:string}){return <span className={'badge '+value.toLowerCase()}>{human(value)}</span>;}
export function Card({title,subtitle,children,action}:{title?:string;subtitle?:string;children:ReactNode;action?:ReactNode}){return <section className="card">{title&&<div className="card-head"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div>{action}</div>}{children}</section>;}
export function Table({rows,columns,onRow}:{rows:any[];columns:ColumnDef<any>[];onRow?:(row:any)=>void}){const table=useReactTable({data:rows,columns,getCoreRowModel:getCoreRowModel()});if(!rows.length)return <div className="empty">No records match this view.</div>;return <div className="table-wrap"><table><thead>{table.getHeaderGroups().map(g=><tr key={g.id}>{g.headers.map(h=><th key={h.id}>{flexRender(h.column.columnDef.header,h.getContext())}</th>)}</tr>)}</thead><tbody>{table.getRowModel().rows.map(r=><tr key={r.id} className={onRow?'clickable':''} onClick={()=>onRow?.(r.original)}>{r.getVisibleCells().map(c=><td key={c.id}>{flexRender(c.column.columnDef.cell,c.getContext())}</td>)}</tr>)}</tbody></table></div>;}
export function Pager({page,total,size,setPage}:{page:number;total:number;size:number;setPage:(p:number)=>void}){return <div className="pager"><span>{total?`${(page-1)*size+1}–${Math.min(page*size,total)} of ${total.toLocaleString()}`:'0 results'}</span><Button size="sm" variant="outline" disabled={page<=1} onClick={()=>setPage(page-1)} aria-label="Previous page"><ChevronLeft size={15}/></Button><Button size="sm" variant="outline" disabled={page*size>=total} onClick={()=>setPage(page+1)} aria-label="Next page"><ChevronRight size={15}/></Button></div>;}
export function Chart({option,height=260}:{option:echarts.EChartsOption;height?:number}){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{if(!ref.current)return;const chart=echarts.init(ref.current);chart.setOption(option);const resize=new ResizeObserver(()=>chart.resize());resize.observe(ref.current);return()=>{resize.disconnect();chart.dispose();};},[option]);return <div ref={ref} style={{height,width:'100%'}} role="img" aria-label="Data chart"/>;}
export function Fields({data}:{data:any}){return <dl className="fields">{Object.entries(data||{}).map(([k,v])=><div key={k}><dt>{human(k)}</dt><dd>{v===null?'Not recorded':typeof v==='object'?JSON.stringify(v):String(v)}</dd></div>)}</dl>;}
export function Notice({children}:{children:ReactNode}){return <div className="notice"><AlertCircle size={17}/><div>{children}</div></div>;}
