import {useEffect,useRef,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import cytoscape from 'cytoscape';
import {Maximize,Plus,Minus,ArrowUpRight,GitBranch} from 'lucide-react';
import {useApi,human,pct} from '../api';
import {State,Card,Chart,Notice,Fields,Badge} from '../components/common';
import {Button} from '../components/ui/button';
import {PageTitle} from './System';
import type {SuccessorLink} from '../types';
const BASE_STYLE:any[]=[{selector:'node',style:{label:'data(label)','font-size':10,color:'#32485e','text-valign':'bottom','text-margin-y':8,'background-color':'#7aa5fa',width:27,height:27,'border-width':3,'border-color':'#ffffff'}},{selector:'node[type="provider"]',style:{'background-color':'#25324a',width:36,height:36}},{selector:'node[type="facility"]',style:{'background-color':'#40958e',shape:'round-rectangle',width:34,height:34}},{selector:'node[type="owner"]',style:{'background-color':'#b18355',shape:'diamond',width:34,height:34}},{selector:'node[type="claim"]',style:{'background-color':'#c9d8fb',width:18,height:18}},{selector:'node[type="member"]',style:{width:16,height:16,'font-size':7,'background-color':'#9fb3c3'}},{selector:'node[member_class="existing"]',style:{'background-color':'#7aa59a'}},{selector:'node[member_class="new_unrelated"]',style:{'background-color':'#c98a5b'}},{selector:'node[member_class="new_related"]',style:{'background-color':'#a7bccc'}},{selector:'node[member_class="pending_confirmation"]',style:{'background-color':'#d9b45f','border-color':'#9b7f3d','border-width':2}},{selector:'node[member_class="simulated_denial"]',style:{'background-color':'#b0463c','shape':'triangle'}},{selector:'node[member_class="simulated_confirmation"]',style:{'background-color':'#4d846c','shape':'round-rectangle'}},{selector:'edge',style:{width:1.4,'line-color':'#ccd8e1','curve-style':'bezier','target-arrow-shape':'triangle','target-arrow-color':'#ccd8e1','arrow-scale':.6}},{selector:'edge[type="possible_successor"]',style:{width:3,'line-style':'dashed','line-color':'#c56a47','target-arrow-color':'#c56a47',label:'data(score)','font-size':9,color:'#ab593e','text-background-color':'#fff','text-background-opacity':1,'text-background-padding':2}},{selector:'edge[type="billed_in_window"]',style:{'line-color':'#e3c3ad','target-arrow-shape':'none'}},{selector:'edge[type="billed_before_window"]',style:{'line-color':'#bcd5cc','target-arrow-shape':'none'}},{selector:':selected',style:{'border-color':'#e6ae66','border-width':5,'line-color':'#d1944b'}}];
const DEFAULT_LEGEND=['● Provider','■ Facility','◆ Owner','● Claim / member','┅ Possible successor'];
export function NetworkCanvas({data,onSelect,legend=DEFAULT_LEGEND,label='Interactive source relationship graph'}:{data:any;onSelect:(d:any)=>void;legend?:string[];label?:string}){const ref=useRef<HTMLDivElement>(null);const graph=useRef<cytoscape.Core|null>(null);useEffect(()=>{if(!ref.current)return;const cy=cytoscape({container:ref.current,elements:[...data.nodes,...data.edges],layout:{name:'preset'},style:BASE_STYLE,minZoom:.15,maxZoom:3});cy.on('tap','node, edge',e=>onSelect(e.target.data()));graph.current=cy;
  // Lay out (and fit) only after the container has been measured; laying out at construction used a zero-size viewport.
  const frame=requestAnimationFrame(()=>{cy.resize();cy.layout({name:'cose',animate:false,nodeRepulsion:()=>150000,idealEdgeLength:()=>100,fit:true,padding:35} as any).run();});
  const observer=new ResizeObserver(()=>cy.resize());observer.observe(ref.current);return()=>{cancelAnimationFrame(frame);observer.disconnect();cy.destroy();};},[data]);return <div className="graph-wrap"><div ref={ref} className="graph-canvas" aria-label={label}/><div className="graph-controls"><Button variant="outline" size="sm" onClick={()=>graph.current?.zoom((graph.current?.zoom()||1)*1.2)} aria-label="Zoom in"><Plus size={16}/></Button><Button variant="outline" size="sm" onClick={()=>graph.current?.zoom((graph.current?.zoom()||1)/1.2)} aria-label="Zoom out"><Minus size={16}/></Button><Button variant="outline" size="sm" onClick={()=>graph.current?.fit(undefined,35)} aria-label="Fit graph"><Maximize size={16}/></Button></div><div className="graph-legend">{legend.map(l=><span key={l}>{l}</span>)}</div></div>;}

const COMPONENT_LABELS:Record<string,string>={patient_overlap:'Patient panel overlap',shared_identifiers:'Shared identifiers',billing_similarity:'Billing fingerprint',referral_overlap:'Referral source reuse',timing:'Timing'};
export function PhoenixBreakdown({link,weights}:{link:SuccessorLink;weights?:Record<string,number>}){const d=link.details;return <div className="phoenix-breakdown"><div className="phoenix-head"><div><span className="eyebrow">POSSIBLE SUCCESSOR · SIMILARITY SCORE</span><strong>{link.score.toFixed(2)}</strong><small>Not a probability of misconduct · {link.detector_version}</small></div><Badge value={link.flagged?'flagged':'not_flagged'}/></div><p className="muted"><Link className="text-link" to={'/network?entity='+link.predecessor_id}>{link.predecessor_id}</Link> ({link.predecessor_name}) was <strong>{d.predecessor_status}</strong> on {d.predecessor_status_date}; <Link className="text-link" to={'/network?entity='+link.successor_id}>{link.successor_id}</Link> ({link.successor_name}) began {d.days_between} days later.</p>{Object.entries(COMPONENT_LABELS).map(([k,label])=>{const v=link.components[k];return <div className="factor" key={k}><span>{label}{weights?` · weight ${weights[k]}`:''}</span><strong>{v==null?'Unavailable':v.toFixed(2)}</strong><div><i style={{width:`${(v||0)*100}%`}}/></div></div>;})}<dl className="fields"><div><dt>Matched identifiers</dt><dd>{Object.keys(d.matched_identifiers).length?Object.keys(d.matched_identifiers).map(human).join(', '):'None'} (compared: {d.compared_identifiers.map(human).join(', ')||'none'})</dd></div><div><dt>Shared patients</dt><dd>{d.shared_member_count} of {d.predecessor_members} predecessor / {d.successor_members} successor members</dd></div><div><dt>Shared procedure codes</dt><dd>{d.shared_procedure_codes.join(', ')||'None'}</dd></div><div><dt>Shared referrers</dt><dd>{d.shared_referrers.join(', ')||'None'}</dd></div><div><dt>Unavailable components</dt><dd>{d.unavailable_components.map(human).join(', ')||'None'}</dd></div>{d.documented_acquisition&&<div><dt>Documented acquisition</dt><dd>{d.documented_acquisition} · may legitimately explain the overlap</dd></div>}{d.predecessor_investigation_history.length>0&&<div><dt>Predecessor history (context only)</dt><dd>{d.predecessor_investigation_history.join(', ')} · not transferred to the successor</dd></div>}</dl>{link.case_id&&<Link className="text-link" to={'/cases/'+link.case_id}>Open consolidated case <ArrowUpRight size={13}/></Link>}</div>;}

function LinkInspector({linkId}:{linkId:string}){const q=useApi<SuccessorLink>('/phoenix/links/'+linkId);return <State query={q}>{l=><PhoenixBreakdown link={l}/>}</State>;}

export function SuccessorBanner({providerId}:{providerId:string}){const enabled=/^P\d+$/.test(providerId);const preds=useApi<{items:SuccessorLink[]}>('/providers/'+providerId+'/predecessors',false,enabled);const succs=useApi<{items:SuccessorLink[]}>('/providers/'+providerId+'/successors',false,enabled);const links=[...(preds.data?.items||[]),...(succs.data?.items||[])].filter(l=>l.flagged);if(!links.length)return null;return <div className="phoenix-banner" role="status"><GitBranch size={17}/><div>{links.map(l=><p key={l.link_id}><strong>Possible successor relationship:</strong> {l.predecessor_id} ({l.details.predecessor_status}) → {l.successor_id} · similarity {l.score.toFixed(2)}. {l.case_id&&<Link className="text-link" to={'/cases/'+l.case_id}>Review case <ArrowUpRight size={12}/></Link>} <Link className="text-link" to={'/network?entity='+l.successor_id}>View graph edge</Link></p>)}</div></div>;}

export function NetworkPage(){const [params]=useSearchParams();const [entity,setEntity]=useState(params.get('entity')||'P0001');const [draft,setDraft]=useState(entity);const [nodeType,setNodeType]=useState('');const [relation,setRelation]=useState('');const [date,setDate]=useState('');const [selection,setSelection]=useState<any>(null);useEffect(()=>{const e=params.get('entity');if(e){setEntity(e);setDraft(e);setSelection(null);}},[params]);const query=useApi('/network/'+encodeURIComponent(entity)+'?'+new URLSearchParams({node_types:nodeType,relationship_types:relation,...(date?{as_of:date}:{})}));return <><PageTitle title="Nexus network" description="Recorded relationships and possible-successor links"/><div className="filters card"><form onSubmit={e=>{e.preventDefault();setEntity(draft);setSelection(null);}}><input aria-label="Entity ID" value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Provider, facility or claim ID"/><Button type="submit">Explore</Button></form><select aria-label="Node types" value={nodeType} onChange={e=>setNodeType(e.target.value)}><option value="">All entity types</option><option value="provider,facility,owner">Providers, facilities & owners</option><option value="claim,member">Claims & members</option></select><select aria-label="Relationship types" value={relation} onChange={e=>setRelation(e.target.value)}><option value="">All relationships</option>{['owns','affiliated_with','shared_practice_indicator','practice_acquisition','possible_successor','referral','billed_by','service_for','service_at'].map(t=><option key={t} value={t}>{human(t)}</option>)}</select><input type="date" aria-label="As of date" value={date} onChange={e=>setDate(e.target.value)}/></div><SuccessorBanner providerId={entity}/><State query={query}>{d=><div className="graph-grid"><Card title={entity} subtitle={`${d.nodes.length} nodes · ${d.edges.length} edges${d.truncated?' · bounded view':''}`}><NetworkCanvas data={d} onSelect={setSelection}/></Card><div><Card title="Inspector"><div className="p-5">{selection?selection.type==='possible_successor'?<LinkInspector linkId={selection.id}/>:<><Fields data={selection}/>{selection.type==='claim'&&<Link className="text-link" to={'/claims/'+selection.id}>Open claim <ArrowUpRight size={15}/></Link>}{selection.type==='provider'&&<Button variant="outline" onClick={()=>{setEntity(selection.id);setDraft(selection.id);}}>Center on provider</Button>}</>:<div className="empty">Select a node or edge.</div>}</div></Card><Card title="Related cases"><div className="p-5">{d.cases.map((c:any)=><Link className="case-link" key={c.case_id} to={'/cases/'+c.case_id}>{c.title}<ArrowUpRight size={14}/></Link>)}{!d.cases.length&&<p className="muted">None.</p>}</div></Card></div></div>}</State></>;}

export function Forecast(){const [params]=useSearchParams();const [pid,setPid]=useState(params.get('provider')||'P0001');const providers=useApi('/providers?page_size=300');const forecast=useApi('/providers/'+pid+'/forecast');const anomaly=useApi('/providers/'+pid+'/anomalies');const provider=useApi('/providers/'+pid);const models=useApi('/models/status');return <><PageTitle title="Future risk" description="30/60/90-day recurrence of observable billing events"><select aria-label="Select provider" value={pid} onChange={e=>setPid(e.target.value)}>{providers.data?.items.map((p:any)=><option key={p.provider_id} value={p.provider_id}>{p.provider_id} · {p.provider_name}</option>)}</select></PageTitle><SuccessorBanner providerId={pid}/><State query={forecast}>{d=><div className="forecast-grid">{[30,60,90].map(h=>{const p=d.items.find((p:any)=>p.horizon===h);const m=models.data?.items.find((m:any)=>m.model_version===p?.model_version);return <Card key={h} title={`${h}-day horizon`} subtitle={p?`As of ${p.cutoff}`:'No eligible model'}><div className="forecast-number">{p?.value!=null?pct(p.value):'Unavailable'}</div><p className="muted">Event recurrence · not a fraud probability</p><div className="risk-meter"><span style={{width:`${(p?.value||0)*100}%`}}/></div><p className="muted">Held-out PR-AUC: {m?.metadata.test?.pr_auc?.toFixed(3)??'Unavailable'}</p><details><summary>Details</summary><Fields data={p?.details||{reason:d.reason}}/></details></Card>;})}</div>}</State><div className="grid-main"><Card title="Service history"><State query={provider}>{p=><Chart option={{tooltip:{trigger:'axis'},legend:{bottom:0},grid:{left:45,right:60,top:20,bottom:60},xAxis:{type:'category',data:p.trend.map((r:any)=>r.month)},yAxis:[{type:'value',name:'Claims'},{type:'value',name:'Allowed USD'}],series:[{name:'Claims',type:'bar',data:p.trend.map((r:any)=>r.claims),itemStyle:{color:'#c9d8fb',borderRadius:[4,4,0,0]},barMaxWidth:18},{name:'Allowed',type:'line',yAxisIndex:1,data:p.trend.map((r:any)=>r.allowed),showSymbol:false,itemStyle:{color:'#4f86f7'}}]}}/>}</State></Card><Card title="Anomaly model" subtitle="Isolation Forest"><State query={anomaly}>{d=>d.items[0]?<div className="p-5"><span className="eyebrow">Anomaly percentile</span><div className="forecast-number">{(d.items[0].details.anomaly_percentile*100).toFixed(1)}</div><p className="muted">Raw score: {d.items[0].value.toFixed(4)} · not a probability</p><details><summary>Features</summary><Fields data={d.items[0].details.signals}/></details></div>:<div className="empty">{d.reason}</div>}</State></Card></div></>;}
