import {useState} from 'react';
import {Link} from 'react-router-dom';
import {useMutation,useQueryClient} from '@tanstack/react-query';
import {ArrowUpRight,FlaskConical,FileQuestion,MailQuestion,Layers} from 'lucide-react';
import {api,useApi,human,money,pct,num} from '../api';
import {State,Card,Table,Badge,Notice} from '../components/common';
import {Button} from '../components/ui/button';
import {PhoenixBreakdown} from './Intelligence';
import type {Case,Finding,NextEvidence,Recommendation,Simulation,EvidenceRequest,Confirmation,SuccessorLink} from '../types';

const SOURCE_LABEL:Record<string,string>={synthetic_default_assumption:'Synthetic default assumption',insufficient_history:'Insufficient history (default used)',synthetic_historical_estimate:'Synthetic historical estimate'};
const position=(p:number|null)=>p==null?'Not queued':`#${p}`;

function OutcomeCell({label,o,current}:{label:string;o:{priority:number;queue_position:number|null;in_capacity:boolean};current:{in_capacity:boolean}}){return <div className="outcome"><span>{label}</span><strong>{o.priority.toFixed(1)}</strong><small>{position(o.queue_position)} · {o.in_capacity?'within capacity':'outside capacity'}{o.in_capacity!==current.in_capacity&&' · crosses boundary'}</small></div>;}

export function SimulationPreview({sim,onClose}:{sim:Simulation;onClose:()=>void}){return <div className="hypothetical" role="region" aria-label="Hypothetical simulation"><div className="hypothetical-head"><strong>{sim.label}</strong><Button size="sm" variant="ghost" onClick={onClose}>Close preview</Button></div><p className="muted">If verified evidence <strong>{sim.outcome==='explains'?'explains':'supports'}</strong> this finding (capacity {sim.capacity}):</p><div className="outcome-grid"><OutcomeCell label="Current" o={sim.original} current={sim.original}/><OutcomeCell label="Hypothetical" o={sim.simulated} current={sim.original}/></div>{sim.entering_top_k.length>0&&<p className="muted">Would enter the top {sim.capacity}: {sim.entering_top_k.map(c=><Link key={c.case_id} className="text-link" to={'/cases/'+c.case_id}>{c.title||c.case_id}</Link>)}</p>}{sim.leaving_top_k.length>0&&<p className="muted">Would leave the top {sim.capacity}: {sim.leaving_top_k.map(c=><Link key={c.case_id} className="text-link" to={'/cases/'+c.case_id}>{c.title||c.case_id}</Link>)}</p>}<details><summary>Factor breakdown (current → hypothetical)</summary><dl className="fields">{Object.keys(sim.original.factors).map(k=><div key={k}><dt>{human(k)}</dt><dd>{Number(sim.original.factors[k]).toFixed(1)} → {Number(sim.simulated.factors[k]).toFixed(1)}</dd></div>)}</dl></details></div>;}

function RecommendationCard({rec,caseId,capacity,current}:{rec:Recommendation;caseId:string;capacity:number;current:NextEvidence['current']}){const client=useQueryClient();const [sim,setSim]=useState<Simulation|null>(null);const simulate=useMutation({mutationFn:(outcome:string)=>api<Simulation>(`/cases/${caseId}/simulate`,{finding_id:rec.finding_id,outcome,capacity,evidence_type:rec.evidence_type}),onSuccess:setSim});const request=useMutation({mutationFn:()=>api(`/cases/${caseId}/evidence-requests`,{finding_id:rec.finding_id,evidence_type:rec.evidence_type,...(rec.subject_claim_id?{claim_id:rec.subject_claim_id}:{})}),onSuccess:()=>client.invalidateQueries()});const done:any=request.data;return <article className="rec-card"><div className="finding-top"><span className="rank-number">{rec.rank}</span><strong>{rec.label}</strong>{rec.crosses_capacity_boundary&&<Badge value="crosses_capacity"/>}</div><p className="muted">Addresses <strong>{human(rec.finding_type)}</strong> ({rec.finding_severity.toLowerCase()} severity){rec.subject_claim_id&&<> · claim <Link className="text-link" to={'/claims/'+rec.subject_claim_id}>{rec.subject_claim_id}</Link></>}. <span className="mono">{rec.finding_id}</span></p><div className="rec-why"><p><b>If it explains:</b> {rec.if_explains}</p><p><b>If it supports:</b> {rec.if_supports}</p></div><div className="outcome-grid"><OutcomeCell label="Current" o={current} current={current}/><OutcomeCell label={`Explains (${pct(rec.p_benign,0)})`} o={rec.outcomes.explains} current={current}/><OutcomeCell label={`Supports (${pct(1-rec.p_benign,0)})`} o={rec.outcomes.supports} current={current}/></div><div className="rec-meta"><span>{SOURCE_LABEL[rec.probability_source]}{rec.history_count?` · n=${rec.history_count}`:''}</span><span>~{rec.estimated_days} days</span><span>Decision-change probability {pct(rec.decision_change_probability,0)}</span><span>Expected shift {rec.expected_absolute_shift.toFixed(1)} pts</span><span>Value {rec.decision_value.toFixed(3)}</span>{rec.open_requests>0&&<span>{rec.open_requests} open</span>}</div><div className="rec-actions"><Button size="sm" onClick={()=>request.mutate()} disabled={request.isPending||done!=null}><FileQuestion size={14}/>{rec.evidence_type==='member_confirmation'?'Generate simulated notice':done?.duplicate?'Already requested':done?'Requested':'Request evidence'}</Button><Button size="sm" variant="outline" onClick={()=>simulate.mutate('explains')} disabled={simulate.isPending}><FlaskConical size={14}/>Simulate explains finding</Button><Button size="sm" variant="outline" onClick={()=>simulate.mutate('supports')} disabled={simulate.isPending}><FlaskConical size={14}/>Simulate supports concern</Button></div>{(request.error||simulate.error)&&<p className="error">{(request.error||simulate.error)?.message}</p>}{sim&&<SimulationPreview sim={sim} onClose={()=>setSim(null)}/>}</article>;}

export function NextEvidencePanel({caseId}:{caseId:string}){const [capacity,setCapacity]=useState(10);const q=useApi<NextEvidence>(`/cases/${caseId}/next-evidence?capacity=${capacity}`);return <Card title="Next best evidence" subtitle="Which request is most likely to change a review decision, given investigator capacity"><div className="p-5"><div className="filters inline"><label className="muted">Investigator capacity (K) <input aria-label="Recommendation capacity" type="number" min={1} max={100} value={capacity} onChange={e=>setCapacity(Math.max(1,Math.min(100,Number(e.target.value)||1)))}/></label></div><State query={q}>{d=><><Notice>{d.notice} Scores come from the live SIU scorer ({d.scorer}); simulations never save anything.</Notice><div className="outcome-grid single"><OutcomeCell label="Current priority" o={d.current} current={d.current}/></div>{d.recommendations.map((r:Recommendation)=><RecommendationCard key={r.finding_id+r.evidence_type} rec={r} caseId={caseId} capacity={capacity} current={d.current}/>)}{!d.recommendations.length&&<div className="empty">No applicable evidence requests remain for the active findings.</div>}{d.outstanding.length>0&&<p className="muted">Outstanding requests: {d.outstanding.map((o:NextEvidence["outstanding"][number])=>`${human(o.evidence_type)} (${o.open_requests})`).join(', ')}.</p>}<details><summary>How recommendations are ranked</summary><p className="muted">{d.formula}. The signed spec heuristic and decision-change probability are reported separately. {d.probability_note} Catalog {d.catalog_version}; considered {d.considered} options.</p></details></>}</State></div></Card>;}

function OutcomeForm({req}:{req:EvidenceRequest}){const client=useQueryClient();const [status,setStatus]=useState(req.evidence_type==='member_confirmation'?'VERIFIED_SUPPORTS':'VERIFIED_EXPLAINS');const [notes,setNotes]=useState('');const m=useMutation({mutationFn:()=>api(`/evidence-requests/${req.request_id}/outcome`,{status,notes}),onSuccess:()=>{client.invalidateQueries();setNotes('');}});const needsNotes=status.startsWith('VERIFIED');return <div className="resolution-form"><label>Reviewed outcome<select aria-label={`Outcome for ${req.request_id}`} value={status} onChange={e=>setStatus(e.target.value)}>{req.status==='REQUESTED'&&<option value="RECEIVED">Received · awaiting review</option>}<option value="VERIFIED_EXPLAINS">Verified · explains the finding</option><option value="VERIFIED_SUPPORTS">Verified · supports the concern</option><option value="INCONCLUSIVE">Inconclusive</option><option value="WITHDRAWN">Withdrawn</option></select></label><textarea aria-label="Review notes" rows={2} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="What did the reviewed document show? (at least 10 characters for verified outcomes)"/>{m.error&&<p className="error">{m.error.message}</p>}<Button size="sm" disabled={m.isPending||(needsNotes&&notes.trim().length<10)} onClick={()=>m.mutate()}>Record reviewed outcome</Button><p className="muted">A document alone never resolves a finding; this records your reviewed decision and recalculates priority through the SIU scorer.</p></div>;}

export function RequestsPanel({caseId}:{caseId:string}){const q=useApi<{items:EvidenceRequest[]}>(`/cases/${caseId}/evidence-requests`);return <Card title="Evidence requests" subtitle="Lifecycle: requested → received → reviewed"><State query={q}>{d=>d.items.length?<div className="p-5">{d.items.map((r:EvidenceRequest)=><details key={r.request_id} className="evidence-record" open={['REQUESTED','RECEIVED'].includes(r.status)}><summary><span><strong>{human(r.evidence_type)}</strong>{r.subject_id&&<> · {r.subject_id}</>}<small>{r.request_id} · {r.requested_by} · {new Date(r.created_at).toLocaleString()}</small></span><Badge value={r.status}/></summary><p className="muted">Finding <span className="mono">{r.finding_id}</span> · estimated {r.estimated_days} days · P(explains) {pct(r.estimated_p_benign,0)} ({SOURCE_LABEL[r.probability_source]||r.probability_source})</p>{r.review_notes&&<p className="muted">Review: {r.review_notes} — {r.reviewer}</p>}{['REQUESTED','RECEIVED'].includes(r.status)&&<OutcomeForm req={r}/>}</details>)}</div>:<div className="empty">No evidence requested yet. Use Next best evidence to request the most useful document.</div>}</State></Card>;}

const CONFIRMABLE=new Set(['stolen_id_batch','member_id_possibly_compromised','missing_encounter_indicator']);
export function confirmableClaims(c:Case){const ids=new Set<string>();c.findings.filter(f=>CONFIRMABLE.has(f.finding_type)&&['ACTIVE','UNRESOLVED','ESCALATED'].includes(f.status)).forEach(f=>f.related_claim_ids.forEach(id=>ids.add(id)));return c.claims.filter(cl=>ids.has(cl.claim_id));}

function ConfirmationCard({c}:{c:Confirmation}){const client=useQueryClient();const respond=useMutation({mutationFn:(response:string)=>api(`/confirmations/${c.confirmation_id}/response`,{response}),onSuccess:()=>client.invalidateQueries()});return <article className="finding"><div className="finding-top"><span className="engine-tag">Simulated member confirmation</span><Badge value={c.response}/><Badge value={c.request_status}/></div><pre className="notice-text">{c.notice_text}</pre><p className="muted">Claim <Link className="text-link" to={'/claims/'+c.claim_id}>{c.claim_id}</Link> · member {c.member_id} · {c.confirmation_id}</p>{c.response==='PENDING'&&<div className="rec-actions"><span className="muted">Simulate the member's answer:</span>{[['YES','Yes'],['NO','No'],['NOT_SURE',"I'm not sure"]].map(([v,l])=><Button key={v} size="sm" variant="outline" disabled={respond.isPending} onClick={()=>respond.mutate(v)}>{l}</Button>)}</div>}{respond.error&&<p className="error">{respond.error.message}</p>}{c.response!=='PENDING'&&['REQUESTED','RECEIVED'].includes(c.request_status)&&<OutcomeForm req={{request_id:c.request_id,evidence_type:'member_confirmation',status:c.request_status} as EvidenceRequest}/>}</article>;}

export function ConfirmationsPanel({caseData}:{caseData:Case}){const client=useQueryClient();const q=useApi<{items:Confirmation[]}>(`/cases/${caseData.case_id}/confirmations`);const [page,setPage]=useState(0);const create=useMutation({mutationFn:(claim_id:string)=>api(`/cases/${caseData.case_id}/confirmations`,{claim_id}),onSuccess:()=>client.invalidateQueries()});const asked=new Set((q.data?.items||[]).map(c=>c.claim_id));const eligible=confirmableClaims(caseData).filter(c=>!asked.has(c.claim_id));const shown=eligible.slice(page*10,page*10+10);return <><Notice>Prototype simulation. No member is ever contacted. Responses are labeled simulated and only affect scoring after an investigator reviews them; three distinct reviewed denials raise a member-batch finding to high severity.</Notice><Card title="Confirmation notices" subtitle="Generated from the stored claim, provider and service date"><State query={q}>{d=><div className="finding-list">{d.items.map((c:Confirmation)=><ConfirmationCard key={c.confirmation_id} c={c}/>)}{!d.items.length&&<div className="empty">No notices generated yet.</div>}</div>}</State></Card><Card title="Claims eligible for confirmation" subtitle={`${eligible.length} claims on member-batch, member-level or missing-encounter findings without a notice`}>{create.error&&<p className="error p-5">{create.error.message}</p>}<Table rows={shown} columns={[{accessorKey:'claim_id',header:'Claim',cell:i=><Link className="text-link" to={'/claims/'+i.getValue()}>{String(i.getValue())}</Link>},{accessorKey:'member_id',header:'Member'},{accessorKey:'service_date',header:'Service date'},{accessorKey:'primary_code',header:'Service'},{accessorKey:'paid_amount_usd',header:'Paid',cell:i=>money(i.getValue())},{id:'notice',header:'',cell:i=><Button size="sm" variant="outline" disabled={create.isPending} onClick={()=>create.mutate(i.row.original.claim_id)}><MailQuestion size={13}/>Generate simulated notice</Button>}]}/>{eligible.length>10&&<div className="pager"><span>{page*10+1}–{Math.min(eligible.length,page*10+10)} of {eligible.length}</span><Button size="sm" variant="outline" disabled={!page} onClick={()=>setPage(page-1)} aria-label="Previous eligible claims">‹</Button><Button size="sm" variant="outline" disabled={(page+1)*10>=eligible.length} onClick={()=>setPage(page+1)} aria-label="Next eligible claims">›</Button></div>}</Card></>;}

export function SpilloverPanel({caseId}:{caseId:string}){const q=useApi(`/cases/${caseId}/spillover`);return <State query={q}>{d=>!d.applicable?<div className="empty">{d.reason}</div>:<><Notice>{d.note}{!d.corroborated&&' The member batch is not yet corroborated by reviewed member confirmations; treat these as low-priority leads.'}</Notice><div className="stats financial">{[['Related claims',num(d.totals.claims)],['Members',num(d.totals.members)],['Billed',money(d.totals.billed)],['Paid',money(d.totals.paid)]].map(([k,v])=><div className="stat" key={k}><span className="stat-label">{k}</span><strong>{v}</strong><small>{k==='Paid'||k==='Billed'?'Leads only · not case exposure':k==='Members'?'Distinct members':'Unique claims'}</small></div>)}</div><Card title="Grouped by provider, claim type and month"><Table rows={d.groups.slice(0,50)} columns={[{accessorKey:'provider_id',header:'Provider',cell:i=><Link className="text-link" to={'/network?entity='+i.getValue()}>{String(i.getValue())}</Link>},{accessorKey:'claim_type',header:'Claim type',cell:i=>human(String(i.getValue()))},{accessorKey:'month',header:'Month'},{accessorKey:'claims',header:'Claims'},{accessorKey:'members',header:'Members'},{accessorKey:'billed',header:'Billed',cell:i=>money(i.getValue())},{accessorKey:'allowed',header:'Allowed',cell:i=>money(i.getValue())},{accessorKey:'paid',header:'Paid',cell:i=>money(i.getValue())}]}/></Card><Card title="Most recent related claims" subtitle={`Showing ${d.claims.length} of ${d.totals.claims}`}><Table rows={d.claims} columns={[{accessorKey:'claim_id',header:'Claim',cell:i=><Link className="text-link" to={'/claims/'+i.getValue()}>{String(i.getValue())}</Link>},{accessorKey:'member_id',header:'Member'},{accessorKey:'provider_id',header:'Provider'},{accessorKey:'service_date',header:'Service date'},{accessorKey:'claim_type',header:'Type'},{accessorKey:'billed_amount_usd',header:'Billed',cell:i=>money(i.getValue())},{accessorKey:'paid_amount_usd',header:'Paid',cell:i=>money(i.getValue())}]}/></Card></>}</State>;}

export function PhoenixCasePanel({finding}:{finding:Finding}){const linkId=(finding as any).context?.link_id;const providerId=finding.entity_id;const q=useApi<{items:SuccessorLink[]}>(`/providers/${providerId}/predecessors`);return <Card title="Possible successor relationship" subtitle="Five transparent similarity components · predecessor context only"><div className="p-5"><State query={q}>{d=>{const link=d.items.find((l:SuccessorLink)=>l.finding_id===finding.finding_id)||d.items.find((l:SuccessorLink)=>l.link_id===linkId);return link?<><PhoenixBreakdown link={link}/><p className="muted">Use Next best evidence to request ownership / acquisition records; record the reviewed outcome to resolve a legitimate successor explanation.</p><Link className="text-link" to={'/network?entity='+link.successor_id}>Inspect the graph edge <ArrowUpRight size={13}/></Link></>:<div className="empty">Successor link details are unavailable.</div>;}}</State></div></Card>;}

export function NextEvidenceSummary({capacity}:{capacity:number}){const q=useApi(`/siu/queue/next-evidence?capacity=${Math.min(capacity,50)}`);return <Card title="Evidence that could change this queue" subtitle="Best request per case near the capacity boundary · hypothetical"><State query={q}>{d=><Table rows={d.items.slice(0,6)} columns={[{accessorKey:'queue_position',header:'#',cell:i=><span className="rank-number">{String(i.getValue()??'–')}</span>},{accessorKey:'title',header:'Case',cell:i=><Link className="text-link" to={'/cases/'+i.row.original.case_id}>{String(i.getValue())}</Link>},{accessorKey:'label',header:'Request next'},{accessorKey:'decision_change_probability',header:'Decision change',cell:i=>pct(i.getValue(),0)},{accessorKey:'crosses_capacity_boundary',header:'Boundary',cell:i=>i.getValue()?<Badge value="crosses_capacity"/>:'—'},{accessorKey:'estimated_days',header:'Days'}]}/>}</State></Card>;}

export function GroupedFindings({findings,render}:{findings:Finding[];render:(f:Finding)=>React.ReactNode}){const [open,setOpen]=useState<Record<string,boolean>>({});const groups=findings.reduce<Record<string,Finding[]>>((acc,f)=>{(acc[f.finding_type]??=[]).push(f);return acc;},{});return <>{Object.entries(groups).map(([type,fs])=>fs.length<=5?fs.map(render):<div key={type} className="finding-group"><div className="group-head"><Layers size={14}/><strong>{fs.length} {human(type)} findings</strong><Button size="sm" variant="ghost" onClick={()=>setOpen({...open,[type]:!open[type]})}>{open[type]?'Show fewer':`Show all ${fs.length}`}</Button></div>{(open[type]?fs:fs.slice(0,3)).map(render)}</div>)}</>;}
