"""SQLAlchemy Core relational schema. CSV columns reflect inspected source headers."""
from sqlalchemy import MetaData, Table, Column, String, Text, Integer, Float, Boolean, Date, DateTime, Numeric, ForeignKey, CheckConstraint, Index, text
from sqlalchemy.dialects.postgresql import JSONB

metadata = MetaData()
SPECS = {
    'members': 'member_id age_band plan_type state city complexity_band synthetic_identity',
    'facilities': 'facility_id facility_name facility_type state city owner_id complexity_mix',
    'providers': 'provider_id provider_name provider_type specialty facility_id state active_from synthetic_identity',
    'encounters': 'encounter_id member_id provider_id facility_id service_start duration_min documented_code documented_complexity encounter_source',
    'claims': 'claim_id member_id provider_id facility_id encounter_id service_date service_start service_duration_min claim_type claim_status submitted_date payment_date primary_code correction_of_claim_id related_claim_id complexity_band billed_amount_usd allowed_amount_usd paid_amount_usd member_responsibility_usd',
    'claim_lines': 'claim_line_id claim_id procedure_code unit_count unit_charge_usd line_billed_usd modifier days_supply days_since_last_fill line_role',
    'supply_items': 'supply_id claim_id claim_line_id supply_code supply_description quantity unit_charge_usd line_billed_usd billing_basis',
    'claim_estimates': 'estimate_id claim_id episode_id estimate_date estimated_billed_usd estimate_scope final_billed_usd difference_usd',
    'referrals': 'referral_id source_provider_id destination_provider_id destination_facility_id member_id referral_date referral_reason referral_source',
    'relationships': 'relationship_id source_id source_type target_id target_type relationship_type effective_from effective_to record_source verification_status',
    'investigation_history': 'investigation_id provider_id facility_id opened_date closed_date outcome outcome_available_date review_channel case_summary',
    'billing_policies': 'policy_id rule_type applicable_claim_types synthetic_rule_description effective_from effective_to limitation policy_origin',
}
# Optional supplementary source files (scenario pack v1). Absent files are allowed; present files are validated like SPECS.
OPTIONAL_SPECS = {
    'provider_profiles': 'provider_id address zip latitude longitude phone practice_owner_id bank_token operating_status status_effective_date enrollment_date profile_source',
    'member_profiles': 'member_id home_zip latitude longitude profile_source',
}
NULLABLE = {'encounter_id', 'payment_date', 'correction_of_claim_id', 'related_claim_id', 'modifier', 'days_supply', 'days_since_last_fill', 'effective_to', 'closed_date', 'outcome_available_date', 'status_effective_date', 'latitude', 'longitude', 'phone', 'practice_owner_id', 'bank_token', 'address', 'zip', 'home_zip'}
INTS = {'duration_min', 'service_duration_min', 'unit_count', 'quantity', 'days_supply', 'days_since_last_fill'}
FLOATS = {'latitude', 'longitude'}
DATES = {'active_from', 'service_date', 'submitted_date', 'payment_date', 'estimate_date', 'referral_date', 'effective_from', 'effective_to', 'opened_date', 'closed_date', 'outcome_available_date', 'status_effective_date', 'enrollment_date'}
FK = {'member_id': 'members.member_id', 'provider_id': 'providers.provider_id', 'facility_id': 'facilities.facility_id', 'encounter_id': 'encounters.encounter_id', 'claim_id': 'claims.claim_id', 'claim_line_id': 'claim_lines.claim_line_id', 'source_provider_id': 'providers.provider_id', 'destination_provider_id': 'providers.provider_id', 'destination_facility_id': 'facilities.facility_id', 'correction_of_claim_id': 'claims.claim_id', 'related_claim_id': 'claims.claim_id'}

def stamp(): return Column('created_at', DateTime(timezone=True), nullable=False, server_default=text('now()'))
def ident(name): return Column(name, String(100), primary_key=True)
def js(name, default='{}'): return Column(name, JSONB, nullable=False, server_default=text(f"'{default}'::jsonb"))

batches = Table('analysis_batches', metadata, ident('batch_id'), Column('kind', String(30), nullable=False), Column('status', String(30), nullable=False), Column('source', Text), Column('checksum', String(64)), Column('progress', Float, default=0), js('report'), stamp(), Column('completed_at', DateTime(timezone=True)))
entities = Table('entities', metadata, ident('entity_id'), Column('entity_type', String(30), nullable=False), Column('label', Text, nullable=False), Column('source_table', String(50), nullable=False))
tables = {}
for name, spec in {**SPECS, **OPTIONAL_SPECS}.items():
    columns = []
    for i, field in enumerate(spec.split()):
        typ = Numeric(16, 2) if field.endswith('_usd') else Integer if field in INTS else Float if field in FLOATS else Date if field in DATES else DateTime(timezone=True) if field == 'service_start' else Text
        args = []
        # Profile tables use the referenced entity ID as their own primary key.
        if field in FK and (i or name in OPTIONAL_SPECS): args.append(ForeignKey(FK[field], deferrable=True, initially='DEFERRED'))
        if name == 'relationships' and field in {'source_id', 'target_id'}: args.append(ForeignKey('entities.entity_id', deferrable=True, initially='DEFERRED'))
        columns.append(Column(field, typ, *args, primary_key=i == 0, nullable=False if i == 0 else field in NULLABLE, index=i > 0 and (field.endswith('_id') or field in {'service_date', 'service_start', 'claim_status'})))
    columns.extend([Column('source_batch_id', String(100), ForeignKey('analysis_batches.batch_id'), nullable=False), Column('source_file', Text, nullable=False), stamp()])
    tables[name] = Table(name, metadata, *columns)
    for field in spec.split():
        if (field.endswith('_usd') and field != 'difference_usd') or field in INTS:
            tables[name].append_constraint(CheckConstraint(f'{field} >= 0', name=f'ck_{name}_{field}_nonnegative'))

jobs = Table('analysis_jobs', metadata, ident('job_id'), Column('kind', String(30), nullable=False), Column('status', String(30), nullable=False, index=True), js('payload'), Column('progress', Float, default=0), Column('attempts', Integer, default=0), Column('error', Text), Column('lease_until', DateTime(timezone=True)), Column('worker_id', Text), js('result'), stamp(), Column('completed_at', DateTime(timezone=True)))
findings = Table('findings', metadata, ident('finding_id'), Column('finding_type', String(80), nullable=False, index=True), Column('engine', String(30), nullable=False), Column('entity_type', String(30), nullable=False), Column('entity_id', Text, ForeignKey('entities.entity_id'), nullable=False, index=True), Column('severity', String(20), nullable=False), Column('score', Float, nullable=False), Column('rule_or_model_version', Text, nullable=False), Column('explanation', Text, nullable=False), Column('data_completeness', Float, nullable=False), js('limitations', '[]'), Column('status', String(30), nullable=False, default='ACTIVE', index=True), Column('batch_id', String(100), ForeignKey('analysis_batches.batch_id'), index=True), stamp())
finding_claims = Table('finding_claims', metadata, Column('finding_id', String(100), ForeignKey('findings.finding_id'), primary_key=True), Column('claim_id', Text, ForeignKey('claims.claim_id'), primary_key=True))
evidence = Table('finding_evidence', metadata, ident('evidence_id'), Column('finding_id', String(100), ForeignKey('findings.finding_id'), nullable=False, index=True), Column('source_table_or_type', Text, nullable=False), Column('source_record_id', Text, nullable=False, index=True), Column('evidence_type', Text, nullable=False), js('observed_value'), js('reference_value_or_context'), Column('record_timestamp', DateTime(timezone=True)), js('provenance'), Column('verification_status', String(40), nullable=False, default='source_record'))
models = Table('model_versions', metadata, ident('model_version'), Column('model_type', Text, nullable=False), Column('status', Text, nullable=False), Column('artifact_path', Text), js('metadata'), stamp())
predictions = Table('risk_predictions', metadata, ident('prediction_id'), Column('provider_id', Text, ForeignKey('providers.provider_id'), nullable=False, index=True), Column('model_version', String(100), ForeignKey('model_versions.model_version')), Column('horizon', Integer, nullable=False), Column('cutoff', Date, nullable=False), Column('value', Float), js('details'), stamp())
cases = Table('cases', metadata, ident('case_id'), Column('title', Text, nullable=False), Column('summary', Text, nullable=False), Column('primary_entity', Text, ForeignKey('entities.entity_id'), index=True), Column('case_status', String(30), nullable=False, default='NEW', index=True), Column('severity', String(20), nullable=False), Column('priority_score', Float, nullable=False, default=0), Column('potential_financial_exposure', Numeric(16, 2), nullable=False, default=0), Column('evidence_strength', Float, nullable=False, default=0), Column('member_impact', Integer, nullable=False, default=0), Column('payment_workflow', String(30), nullable=False), Column('assigned_investigator', Text), js('ranking'), Column('evidence_version', Integer, nullable=False, default=1), stamp(), Column('updated_at', DateTime(timezone=True), nullable=False, server_default=text('now()')))
case_findings = Table('case_findings', metadata, Column('case_id', String(100), ForeignKey('cases.case_id'), primary_key=True), Column('finding_id', String(100), ForeignKey('findings.finding_id'), primary_key=True))
case_entities = Table('case_entities', metadata, Column('case_id', String(100), ForeignKey('cases.case_id'), primary_key=True), Column('entity_id', Text, ForeignKey('entities.entity_id'), primary_key=True))
assignments = Table('case_assignments', metadata, ident('assignment_id'), Column('case_id', String(100), ForeignKey('cases.case_id'), nullable=False), Column('investigator', Text, nullable=False), stamp())
briefs = Table('investigation_briefs', metadata, ident('brief_id'), Column('case_id', String(100), ForeignKey('cases.case_id'), nullable=False, index=True), Column('evidence_version', Integer, nullable=False), Column('kind', Text, nullable=False), Column('mode', Text, nullable=False), js('content'), stamp())
actions = Table('investigator_actions', metadata, ident('action_id'), Column('case_id', String(100), ForeignKey('cases.case_id'), nullable=False), Column('finding_id', String(100), ForeignKey('findings.finding_id')), Column('actor', Text, nullable=False), Column('action_type', Text, nullable=False), Column('explanation', Text, nullable=False), js('previous_state'), js('new_state'), stamp())
audit = Table('audit_events', metadata, ident('event_id'), Column('case_id', String(100), ForeignKey('cases.case_id'), index=True), Column('finding_id', String(100), ForeignKey('findings.finding_id')), Column('actor', Text, nullable=False), Column('action_type', Text, nullable=False), Column('explanation', Text, nullable=False), js('previous_state'), js('new_state'), stamp())
Index('ix_cases_priority', cases.c.priority_score.desc())

# Migration 0002: investigation workflow extensions (Next-Best-Evidence, Member Radar, Phoenix).
evidence_requests = Table('evidence_requests', metadata, ident('request_id'), Column('case_id', String(100), ForeignKey('cases.case_id'), nullable=False, index=True), Column('finding_id', String(100), ForeignKey('findings.finding_id'), nullable=False, index=True), Column('evidence_type', Text, nullable=False), Column('subject_id', Text), Column('status', String(30), nullable=False, index=True), Column('requested_by', Text, nullable=False), Column('estimated_days', Float, nullable=False), Column('estimated_p_benign', Float, nullable=False), Column('probability_source', Text, nullable=False), js('score_snapshot'), Column('justification', Text), Column('reviewer', Text), Column('review_notes', Text), Column('evidence_id', String(100)), Column('outcome_at', DateTime(timezone=True)), stamp(), Column('updated_at', DateTime(timezone=True), nullable=False, server_default=text('now()')))
confirmations = Table('member_confirmations', metadata, ident('confirmation_id'), Column('case_id', String(100), ForeignKey('cases.case_id'), nullable=False, index=True), Column('finding_id', String(100), ForeignKey('findings.finding_id'), nullable=False, index=True), Column('claim_id', Text, ForeignKey('claims.claim_id'), nullable=False, index=True), Column('member_id', Text, ForeignKey('members.member_id'), nullable=False, index=True), Column('request_id', String(100), ForeignKey('evidence_requests.request_id'), nullable=False), Column('notice_text', Text, nullable=False), Column('created_by', Text, nullable=False), Column('simulated', Boolean, nullable=False, default=True), Column('response', String(20), nullable=False, default='PENDING'), Column('response_at', DateTime(timezone=True)), Column('notes', Text), Column('source', Text, nullable=False), stamp())
member_risk = Table('member_risk', metadata, Column('member_id', Text, ForeignKey('members.member_id'), primary_key=True), Column('score', Float), Column('as_of', Date, nullable=False), js('signals'), Column('detector_version', Text, nullable=False), Column('batch_id', String(100), ForeignKey('analysis_batches.batch_id')), stamp())
radar_batches = Table('radar_batches', metadata, Column('provider_id', Text, ForeignKey('providers.provider_id'), primary_key=True), Column('qualified', Boolean, nullable=False), Column('finding_id', String(100), ForeignKey('findings.finding_id')), Column('as_of', Date, nullable=False), js('metrics'), js('checks', '[]'), Column('detector_version', Text, nullable=False), Column('batch_id', String(100), ForeignKey('analysis_batches.batch_id')), stamp())
radar_batch_members = Table('radar_batch_members', metadata, Column('provider_id', Text, ForeignKey('providers.provider_id'), primary_key=True), Column('member_id', Text, ForeignKey('members.member_id'), primary_key=True), Column('first_recent_claim', Date, nullable=False), js('claim_ids', '[]'), Column('prior_relationship', Text), Column('prior_context', Boolean, nullable=False), Column('distance_km', Float), Column('member_score', Float))
successors = Table('provider_successors', metadata, ident('link_id'), Column('predecessor_id', Text, ForeignKey('providers.provider_id'), nullable=False, index=True), Column('successor_id', Text, ForeignKey('providers.provider_id'), nullable=False, index=True), Column('score', Float, nullable=False), Column('flagged', Boolean, nullable=False), js('components'), js('details'), Column('finding_id', String(100), ForeignKey('findings.finding_id')), Column('detector_version', Text, nullable=False), Column('batch_id', String(100), ForeignKey('analysis_batches.batch_id')), stamp(), Column('updated_at', DateTime(timezone=True), nullable=False, server_default=text('now()')))


# Migration 0003: live claims monitoring (stream sessions, per-claim stage coverage, ordered processing events).
STREAM_ACTIVE = ('STARTING', 'RUNNING', 'STOPPING', 'DRAINING')
stream_sessions = Table('stream_sessions', metadata, ident('session_id'), Column('session_number', Integer, nullable=False, unique=True), Column('status', String(20), nullable=False, index=True), js('config'), Column('seed', Integer, nullable=False), Column('scenario_version', Text, nullable=False), Column('intended_count', Integer, nullable=False), Column('generated_count', Integer, nullable=False, default=0), Column('rejected_count', Integer, nullable=False, default=0), Column('max_backlog', Integer, nullable=False, default=0), Column('stop_requested', Boolean, nullable=False, default=False), Column('runner_id', Text), Column('lease_until', DateTime(timezone=True)), js('cohort'), Column('batch_id', String(100), ForeignKey('analysis_batches.batch_id')), Column('last_event', Text), js('error'), stamp(), Column('started_at', DateTime(timezone=True)), Column('stop_requested_at', DateTime(timezone=True)), Column('stopped_at', DateTime(timezone=True)), Column('updated_at', DateTime(timezone=True), nullable=False, server_default=text('now()')))
# Database-level guarantee: at most one session can be active, whatever the number of Start requests or runners.
Index('uq_stream_one_active', text('(true)'), unique=True, postgresql_where=stream_sessions.c.status.in_(STREAM_ACTIVE), _table=stream_sessions)
stream_claims = Table('stream_claims', metadata, Column('claim_id', Text, ForeignKey('claims.claim_id'), primary_key=True), Column('session_id', String(100), ForeignKey('stream_sessions.session_id'), nullable=False, index=True), Column('sequence', Integer, nullable=False), Column('scenario', Text, nullable=False), Column('generated_at', DateTime(timezone=True), nullable=False), Column('ingested_at', DateTime(timezone=True), nullable=False), Column('service_date', Date, nullable=False), Column('analysis_status', String(20), nullable=False, index=True), Column('current_stage', Text), Column('attempts', Integer, nullable=False, default=0), Column('lease_until', DateTime(timezone=True)), Column('next_attempt_at', DateTime(timezone=True)), Column('immediate_at', DateTime(timezone=True)), Column('enrichment_run_id', String(100)), Column('fully_analyzed_at', DateTime(timezone=True)), js('finding_ids', '[]'), js('case_ids', '[]'), Column('error', Text))
Index('uq_stream_claim_sequence', stream_claims.c.session_id, stream_claims.c.sequence, unique=True)
stream_stages = Table('stream_claim_stages', metadata, Column('claim_id', Text, ForeignKey('stream_claims.claim_id'), primary_key=True), Column('stage', String(40), primary_key=True), Column('status', String(20), nullable=False), Column('attempts', Integer, nullable=False, default=0), Column('run_id', String(100)), Column('started_at', DateTime(timezone=True)), Column('completed_at', DateTime(timezone=True)), Column('findings_count', Integer, nullable=False, default=0), Column('reason', Text), Column('error', Text), js('result'), Column('processing_version', Text, nullable=False))
stream_events = Table('stream_events', metadata, Column('event_id', Integer, primary_key=True, autoincrement=True), Column('session_id', String(100), ForeignKey('stream_sessions.session_id'), nullable=False, index=True), Column('event_type', String(40), nullable=False), Column('claim_id', Text), Column('finding_id', Text), Column('case_id', Text), Column('provider_id', Text), Column('stage', Text), Column('message', Text, nullable=False), js('payload'), stamp())
stream_runs = Table('stream_enrichment_runs', metadata, ident('run_id'), Column('session_id', String(100), ForeignKey('stream_sessions.session_id'), nullable=False, index=True), Column('job_id', String(100)), Column('status', String(20), nullable=False), js('claim_ids', '[]'), Column('watermark_sequence', Integer), js('providers', '[]'), js('stage_results'), Column('duration_seconds', Float), Column('error', Text), stamp(), Column('completed_at', DateTime(timezone=True)))
stream_runners = Table('stream_runners', metadata, ident('runner_id'), Column('heartbeat_at', DateTime(timezone=True), nullable=False), Column('host', Text), stamp())

# Migration 0004: policy-governed investigator decisions (recommendations; approvals need an authenticated supervisor).
decisions = Table('policy_decisions', metadata, ident('decision_id'), Column('case_id', String(100), ForeignKey('cases.case_id'), nullable=False, index=True), Column('action', String(40), nullable=False), Column('policy_version', Text, nullable=False), js('evaluation'), js('evidence_refs', '[]'), Column('justification', Text, nullable=False), Column('requested_by', Text, nullable=False), Column('approved_by', Text), Column('status', String(30), nullable=False, index=True), stamp(), Column('updated_at', DateTime(timezone=True), nullable=False, server_default=text('now()')))
