export type RecordData=Record<string,any>;
export interface Page<T=RecordData>{items:T[];total:number;page:number;page_size:number}
export interface Evidence{evidence_id:string;source_table_or_type:string;source_record_id:string;finding_id:string;evidence_type:string;observed_value:RecordData;reference_value_or_context:RecordData;record_timestamp:string|null;provenance:RecordData;verification_status:string}
export interface Finding{finding_id:string;finding_type:string;engine:string;entity_type:string;entity_id:string;related_claim_ids:string[];related_provider_ids:string[];related_facility_ids:string[];severity:'LOW'|'MEDIUM'|'HIGH';anomaly_score_or_rule_result:number;rule_or_model_version:string;evidence_ids:string[];explanation:string;data_completeness:number;limitations:string[];detected_at:string;status:string}
export interface Case extends RecordData{case_id:string;title:string;summary:string;primary_entity:string;case_status:string;severity:string;priority_score:number;potential_financial_exposure:number;findings:Finding[];evidence:Evidence[];claims:RecordData[];allowed_transitions:string[]}
export interface Outcome{priority:number;queue_position:number|null;in_capacity:boolean}
export interface Recommendation{rank:number;finding_id:string;finding_type:string;finding_severity:string;evidence_type:string;label:string;if_explains:string;if_supports:string;subject_claim_id:string|null;estimated_days:number;p_benign:number;probability_source:'synthetic_default_assumption'|'insufficient_history'|'synthetic_historical_estimate';history_count:number;outcomes:{explains:Outcome;supports:Outcome};expected_directed_delta:number;expected_absolute_shift:number;decision_change_probability:number;crosses_capacity_boundary:boolean;legacy_voi:number;decision_value:number;open_requests:number}
export interface NextEvidence{case_id:string;hypothetical:true;capacity:number;current:Outcome&{stored_priority:number;queue_size:number};recommendations:Recommendation[];considered:number;outstanding:{finding_id:string;evidence_type:string;open_requests:number}[];evidence_version:number;scorer:string;formula:string;catalog_version:string;probability_note:string;notice:string}
export interface Simulation{hypothetical:true;label:string;finding_id:string;outcome:string;capacity:number;original:Outcome&{factors:RecordData};simulated:Outcome&{factors:RecordData;severity:string;exposure:number};entering_top_k:{case_id:string;title:string}[];leaving_top_k:{case_id:string;title:string}[]}
export interface EvidenceRequest{request_id:string;case_id:string;finding_id:string;evidence_type:string;subject_id:string|null;status:string;requested_by:string;estimated_days:number;estimated_p_benign:number;probability_source:string;reviewer:string|null;review_notes:string|null;evidence_id:string|null;created_at:string;outcome_at:string|null;duplicate?:boolean}
export interface Confirmation{confirmation_id:string;case_id:string;finding_id:string;claim_id:string;member_id:string;request_id:string;request_status:string;notice_text:string;created_by:string;simulated:boolean;response:'PENDING'|'YES'|'NO'|'NOT_SURE';response_at:string|null;notes:string|null;created_at:string}
export interface SuccessorLink{link_id:string;predecessor_id:string;successor_id:string;predecessor_name:string;successor_name:string;score:number;flagged:boolean;components:Record<string,number|null>;details:RecordData;finding_id:string|null;case_id:string|null;detector_version:string}
export interface RadarCheck{name:string;value:number|null;op:string;threshold:number;required:boolean;evaluable:boolean;passed:boolean}
